### PR TITLE
Add Liu, Calver, Craig ACE '24 paper

### PR DESCRIPTION
**Pull request by david-yz-liu**
Hey @utmandrew, two quick questions:

1. Is the ID (`03Liu24`) appropriate? Wasn't sure what the convention was.
2. Do you want me to add a commented-out duplicate to Michelle's `.bib` entry as well?

### CODE REVIEW

**Comment by utmandrew** [comment]
Thanks, David!

1. 03Liu24 is perfect.
2. I have done so in the past, but only out of habit. I had some idea that it might make it easier for people to take their bibs away with them ... but no one has done that. So I don't know that we really have to continue.

**Comment by utmandrew** [comment]
Review comments:

1. I typically reverse the authors -- or pull them from DBPL, where the auhors are in first last instead of last, first order.  Not a big deal either way.
2. To get the paper to show, you'll need to run _pubs/make_research_table.bash and then add the updated pubs.md to the commit.

**Comment by david-yz-liu** [comment]
Thanks @utmandrew! Somehow I thought the building was automatic, my bad!

**Comment by utmandrew** [comment]
It really should be ... >.>

**Pull request merged**
